//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deployer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deployer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directory.
        /// </summary>
        public static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new path variable.
        /// </summary>
        public static string AddPathVariable {
            get {
                return ResourceManager.GetString("AddPathVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add value.
        /// </summary>
        public static string AddValue {
            get {
                return ResourceManager.GetString("AddValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append.
        /// </summary>
        public static string Append {
            get {
                return ResourceManager.GetString("Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All existing items remain intact while imported items are appended. Note that there is no protection against &quot;duplicate&quot; pre-existing and imported items..
        /// </summary>
        public static string AppendConfigurationDescription {
            get {
                return ResourceManager.GetString("AppendConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string AtoB {
            get {
                return ResourceManager.GetString("AtoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically close after errors.
        /// </summary>
        public static string AutomaticallyCloseAfterError {
            get {
                return ResourceManager.GetString("AutomaticallyCloseAfterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to automatically close the dialog when a copy fails with errors.
        /// </summary>
        public static string AutomaticallyCloseAfterErrorTooltip {
            get {
                return ResourceManager.GetString("AutomaticallyCloseAfterErrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically stop locking processes.
        /// </summary>
        public static string AutomaticallyStopLockingProcesses {
            get {
                return ResourceManager.GetString("AutomaticallyStopLockingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back up config and continue.
        /// </summary>
        public static string BackupAndContinue {
            get {
                return ResourceManager.GetString("BackupAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Created.
        /// </summary>
        public static string BackupCreated {
            get {
                return ResourceManager.GetString("BackupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Deployment.
        /// </summary>
        public static string BeginningDeployment {
            get {
                return ResourceManager.GetString("BeginningDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing configuration items and/or path variables were detected. How do you want to apply the imported configuration?.
        /// </summary>
        public static string ChooseImportMode {
            get {
                return ResourceManager.GetString("ChooseImportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose value(s).
        /// </summary>
        public static string ChooseValues {
            get {
                return ResourceManager.GetString("ChooseValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was exported to:.
        /// </summary>
        public static string ConfigurationExported {
            get {
                return ResourceManager.GetString("ConfigurationExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration imported successfully..
        /// </summary>
        public static string ConfigurationImported {
            get {
                return ResourceManager.GetString("ConfigurationImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete configuration &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteConfiguration {
            get {
                return ResourceManager.GetString("ConfirmDeleteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy details to clipboard.
        /// </summary>
        public static string CopyErrorDetails {
            get {
                return ResourceManager.GetString("CopyErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Files.
        /// </summary>
        public static string CopyingFilesTitle {
            get {
                return ResourceManager.GetString("CopyingFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Settings.
        /// </summary>
        public static string CopySettingsDescription {
            get {
                return ResourceManager.GetString("CopySettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new configuration.
        /// </summary>
        public static string CreateConfiguration {
            get {
                return ResourceManager.GetString("CreateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected configuration.
        /// </summary>
        public static string DeleteConfiguration {
            get {
                return ResourceManager.GetString("DeleteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected path variable.
        /// </summary>
        public static string DeletePathVariable {
            get {
                return ResourceManager.GetString("DeletePathVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        public static string Deploy {
            get {
                return ResourceManager.GetString("Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy encountered {0} errors(s)..
        /// </summary>
        public static string DeployEncounteredErrors {
            get {
                return ResourceManager.GetString("DeployEncounteredErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployer.
        /// </summary>
        public static string Deployer {
            get {
                return ResourceManager.GetString("Deployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployer  {0}.
        /// </summary>
        public static string DeployerTitle {
            get {
                return ResourceManager.GetString("DeployerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy ({0}).
        /// </summary>
        public static string DeployTooltip {
            get {
                return ResourceManager.GetString("DeployTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Directory(s).
        /// </summary>
        public static string DestinationDirectories {
            get {
                return ResourceManager.GetString("DestinationDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of {0}.
        /// </summary>
        public static string DuplicateConfigurationName {
            get {
                return ResourceManager.GetString("DuplicateConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled:.
        /// </summary>
        public static string EnabledSettingDescription {
            get {
                return ResourceManager.GetString("EnabledSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying {0} to {1}.
        /// </summary>
        public static string ErrorCopyingSourceToDestination {
            get {
                return ResourceManager.GetString("ErrorCopyingSourceToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the existing configuration file..
        /// </summary>
        public static string ErrorLoadingExistingConfiguration {
            get {
                return ResourceManager.GetString("ErrorLoadingExistingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restarting process &apos;{0}&apos;.
        /// </summary>
        public static string ErrorRestartingProcess {
            get {
                return ResourceManager.GetString("ErrorRestartingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restarting service &apos;{0}&apos;.
        /// </summary>
        public static string ErrorRestartingService {
            get {
                return ResourceManager.GetString("ErrorRestartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping locking service {0}.
        /// </summary>
        public static string ErrorStoppingLockingService {
            get {
                return ResourceManager.GetString("ErrorStoppingLockingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions list:.
        /// </summary>
        public static string ExclusionsListSettingDescription {
            get {
                return ResourceManager.GetString("ExclusionsListSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a set of file names or patterns to exclude. One exclusion per line. Use * as wildcard.
        ///
        ///For example:
        ///*.exe
        ///*.config
        ///
        ///If a file matches both inclusions and exclusions list, it will be excluded..
        /// </summary>
        public static string ExclusionsListSettingExtendedDescription {
            get {
                return ResourceManager.GetString("ExclusionsListSettingExtendedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error exporting the configuration..
        /// </summary>
        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exists only on other side..
        /// </summary>
        public static string FileExistsOnOtherSize {
            get {
                return ResourceManager.GetString("FileExistsOnOtherSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is newer than matching {1} on other side..
        /// </summary>
        public static string FileIsNewerThanOtherSide {
            get {
                return ResourceManager.GetString("FileIsNewerThanOtherSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is older than matching {1} on other side..
        /// </summary>
        public static string FileIsOlderThanOtherSize {
            get {
                return ResourceManager.GetString("FileIsOlderThanOtherSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches exclusion pattern or does not match inclusion pattern and will not be copied..
        /// </summary>
        public static string FileMatchesExclusionPattern {
            get {
                return ResourceManager.GetString("FileMatchesExclusionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File view options:.
        /// </summary>
        public static string FileViewOptionsSettingDescription {
            get {
                return ResourceManager.GetString("FileViewOptionsSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Deployment.
        /// </summary>
        public static string FinishedDeployment {
            get {
                return ResourceManager.GetString("FinishedDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found locked file: {0}.
        /// </summary>
        public static string FoundLockedFile {
            get {
                return ResourceManager.GetString("FoundLockedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: {0}.
        /// </summary>
        public static string FromSource {
            get {
                return ResourceManager.GetString("FromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path: {0}.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettingsDescription {
            get {
                return ResourceManager.GetString("GeneralSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for graceful shutdown.
        /// </summary>
        public static string GracefulShutdown {
            get {
                return ResourceManager.GetString("GracefulShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error importing the configuration..
        /// </summary>
        public static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include directories:.
        /// </summary>
        public static string IncludeDirectoriesSettingDescription {
            get {
                return ResourceManager.GetString("IncludeDirectoriesSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories are all-or-nothing, meaning that if a source directory is newer than a destination directory, all of its contents will be copied and replace all of the destination contents..
        /// </summary>
        public static string IncludeDirectoriesSettingExtendedDescription {
            get {
                return ResourceManager.GetString("IncludeDirectoriesSettingExtendedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusions list:.
        /// </summary>
        public static string InclusionsListSettingDescription {
            get {
                return ResourceManager.GetString("InclusionsListSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a set of file names or patterns to include. One exclusion per line. Use * as wildcard.
        ///
        ///For example:
        ///*.exe
        ///*.config
        ///
        ///If a file matches both inclusions and exclusions list, it will be excluded..
        /// </summary>
        public static string InclusionsListSettingExtendedDescription {
            get {
                return ResourceManager.GetString("InclusionsListSettingExtendedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string KeyboardShortcutFormat {
            get {
                return ResourceManager.GetString("KeyboardShortcutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        public static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically restart killed processes:.
        /// </summary>
        public static string KilledProcessesSettingDescription {
            get {
                return ResourceManager.GetString("KilledProcessesSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing locking process &apos;{0}&apos;....
        /// </summary>
        public static string KillingLockingProcess {
            get {
                return ResourceManager.GetString("KillingLockingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified at: {0}.
        /// </summary>
        public static string LastModifiedAt {
            get {
                return ResourceManager.GetString("LastModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If file exists on left but not on right:.
        /// </summary>
        public static string LeftButNotRightSettingDescription {
            get {
                return ResourceManager.GetString("LeftButNotRightSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If destination file is locked:.
        /// </summary>
        public static string LockedFileOptionSettingDescription {
            get {
                return ResourceManager.GetString("LockedFileOptionSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Unable to detect or automatically stop locking processes when copying to a remote server..
        /// </summary>
        public static string LockedFileOptionSettingExtendedDescription {
            get {
                return ResourceManager.GetString("LockedFileOptionSettingExtendedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked File Settings.
        /// </summary>
        public static string LockedFileSettingsDescription {
            get {
                return ResourceManager.GetString("LockedFileSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected configuration item down.
        /// </summary>
        public static string MoveConfigurationDown {
            get {
                return ResourceManager.GetString("MoveConfigurationDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected configuration item up.
        /// </summary>
        public static string MoveConfigurationUp {
            get {
                return ResourceManager.GetString("MoveConfigurationUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And a new empty configuration has been created..
        /// </summary>
        public static string NewConfigCreated {
            get {
                return ResourceManager.GetString("NewConfigCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Configuration.
        /// </summary>
        public static string NewConfigurationName {
            get {
                return ResourceManager.GetString("NewConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If file is newer on left:.
        /// </summary>
        public static string NewerOnLeftSettingDescription {
            get {
                return ResourceManager.GetString("NewerOnLeftSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If file is newer on right:.
        /// </summary>
        public static string NewerOnRightSettingDescription {
            get {
                return ResourceManager.GetString("NewerOnRightSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next configuration to deploy:.
        /// </summary>
        public static string NextConfigurationSettingDescription {
            get {
                return ResourceManager.GetString("NextConfigurationSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose another configuration to deploy automatically after deploying the current config..
        /// </summary>
        public static string NextConfigurationSettingExtendedDescription {
            get {
                return ResourceManager.GetString("NextConfigurationSettingExtendedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment found no files to copy. No operation was performed..
        /// </summary>
        public static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old configuration file has been backed up to:.
        /// </summary>
        public static string OldConfigurationAvailableAt {
            get {
                return ResourceManager.GetString("OldConfigurationAvailableAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config file location.
        /// </summary>
        public static string OpenConfigFileLocation {
            get {
                return ResourceManager.GetString("OpenConfigFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to enable or uncheck to disable this option.
        /// </summary>
        public static string OptionSelectedToolTip {
            get {
                return ResourceManager.GetString("OptionSelectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist.
        /// </summary>
        public static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Variables.
        /// </summary>
        public static string PathVariables {
            get {
                return ResourceManager.GetString("PathVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to Deploy.
        /// </summary>
        public static string PreparingToDeploy {
            get {
                return ResourceManager.GetString("PreparingToDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh ({0}).
        /// </summary>
        public static string RefreshTooltip {
            get {
                return ResourceManager.GetString("RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove directory.
        /// </summary>
        public static string RemoveDirectory {
            get {
                return ResourceManager.GetString("RemoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove value.
        /// </summary>
        public static string RemoveValue {
            get {
                return ResourceManager.GetString("RemoveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes all existing configuration items and path variables, and replaces them with the imported items..
        /// </summary>
        public static string ReplaceConfigurationDescription {
            get {
                return ResourceManager.GetString("ReplaceConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting killed process &apos;{0}&apos;....
        /// </summary>
        public static string RestartingKilledProcess {
            get {
                return ResourceManager.GetString("RestartingKilledProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting Stopped Processes and Services.
        /// </summary>
        public static string RestartingStoppedProcessesTitle {
            get {
                return ResourceManager.GetString("RestartingStoppedProcessesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting stopped service &apos;{0}&apos;....
        /// </summary>
        public static string RestartingStoppedService {
            get {
                return ResourceManager.GetString("RestartingStoppedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0} bytes.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped locked files.
        /// </summary>
        public static string SkipLockedFiles {
            get {
                return ResourceManager.GetString("SkipLockedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Directory(s).
        /// </summary>
        public static string SourceDirectories {
            get {
                return ResourceManager.GetString("SourceDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Locking Processes and Services.
        /// </summary>
        public static string StoppingLockingProcessesTitle {
            get {
                return ResourceManager.GetString("StoppingLockingProcessesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping locking service &apos;{0}&apos;....
        /// </summary>
        public static string StoppingLockingService {
            get {
                return ResourceManager.GetString("StoppingLockingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to handle locking services:.
        /// </summary>
        public static string StopServiceMethodSettingDescription {
            get {
                return ResourceManager.GetString("StopServiceMethodSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how to handle Windows services which are locking the destination file. Note that normal (non-service) processes are never killed gracefully..
        /// </summary>
        public static string StopServiceMethodSettingExtendedDescription {
            get {
                return ResourceManager.GetString("StopServiceMethodSettingExtendedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled..
        /// </summary>
        public static string TheOperationWasCanceled {
            get {
                return ResourceManager.GetString("TheOperationWasCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To: {0}.
        /// </summary>
        public static string ToDestination {
            get {
                return ResourceManager.GetString("ToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Unable to detect locking processes on remote server..
        /// </summary>
        public static string UnableToDetectRemoteLockingProcesses {
            get {
                return ResourceManager.GetString("UnableToDetectRemoteLockingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unhandled error..
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update live:.
        /// </summary>
        public static string UpdateLiveSettingDescription {
            get {
                return ResourceManager.GetString("UpdateLiveSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all files.
        /// </summary>
        public static string ViewAllFiles {
            get {
                return ResourceManager.GetString("ViewAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View files which will be excluded.
        /// </summary>
        public static string ViewExcludedFiles {
            get {
                return ResourceManager.GetString("ViewExcludedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View last error details.
        /// </summary>
        public static string ViewLastErrorDetails {
            get {
                return ResourceManager.GetString("ViewLastErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View files which will be copied.
        /// </summary>
        public static string ViewPendingFiles {
            get {
                return ResourceManager.GetString("ViewPendingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View session log....
        /// </summary>
        public static string ViewSessionLog {
            get {
                return ResourceManager.GetString("ViewSessionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Settings.
        /// </summary>
        public static string ViewSettingsDescription {
            get {
                return ResourceManager.GetString("ViewSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for locking processes to stop.
        /// </summary>
        public static string WaitForLockingProcesses {
            get {
                return ResourceManager.GetString("WaitForLockingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for locking process &apos;{0}&apos; to stop....
        /// </summary>
        public static string WaitingForLockingProcessToStop {
            get {
                return ResourceManager.GetString("WaitingForLockingProcessToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
